pipeline:
  publish:
    image: plugins/docker:17.05
    repo: plugins/gcr
# rationalize version w/drone-docker tags
    tags: [ "latest", "17", "17.05" ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

